cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    "\uB85C\uADF8\uC778":
      name: "\uB85C\uADF8\uC778\uD14C\uC2A4\uD2B8"
      password: $2b$12$RaTE/OtcGw99JfTzYSCfxeeZt9XwiheR4fJKkS3eQsmE6lFeJm0E.
    "\uC624\uAD6C":
      name: "\uC624\uAD6C\uC758\uBAA8\uD5D8"
      password: $2b$12$YPXq1/7SUTCvHXD/RbZvIe5sS/ynyKdEi2yokvo5tywTfQbM.PL3y
preauthorized:
  emails:
  - melsby@gmail.com


